name = input("Adınız Soyadınız:")
student_id = input("Öğrenci Numaranız:")
department = input("Bölümünüz:")
github_username = input("GitHub Kullanıcı Adınız:")
programming_goal = input("Programlama Hedefiniz:")

print("\n" + "="*35)
print("ÖĞRENCİ TANITIM KARTI")
print("="*35)
print(f"İsim : {name}")
print(f"Öğrenci No : {student_id}")
print(f"Bölüm : {department}")
print(f"GitHub : {github_username}")
print(f"Hedef : {programming_goal}")
print("="*35)
